version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Wait for Mongo to start
          command: dockerize -wait tcp://127.0.0.1:27017 -timeout 120s
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - run: npm eslint
workflows:
    build-and-test:
      jobs:
        - build-and-test